initialize Audit EntitySet on @PostConstruct
openlattice/conductor pull request #21
Opened 2017-05-04 01:11 UTC by UnsungHero97

2017-05-04 21:18 UTC, geekbeast requested changes

2017-05-04 21:18 UTC, geekbeast commented on src/main/java/com/kryptnostic/conductor/PlasmaCoupling.java
> +        AuditEntitySet.initialize( dataSourceManager, entityDataModelManager );
Having a class called AuditEntitySet seems like a bad precedent and pattern. I think most of it could be resolved by renaming to AuditEntitySetUtils

2017-05-04 22:07 UTC, UnsungHero97 commented on src/main/java/com/kryptnostic/conductor/PlasmaCoupling.java
> +        AuditEntitySet.initialize( dataSourceManager, entityDataModelManager );
Done.

2017-05-06 00:39 UTC, UnsungHero97 commented
Closing as this is no longer relevant. `@PostConstruct` will move into `conductor-client`.

2017-05-06 00:39 UTC, closed without merging